import { Heading, Text, Button, Card } from 'frosted-ui'
import { BookOpen, Sparkles } from 'lucide-react'

export default function AuthPage() {
  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50">
      <div className="max-w-md w-full mx-auto px-4">
        <Card className="p-8 text-center">
          <div className="mb-6">
            <div className="mx-auto w-16 h-16 bg-blue-100 rounded-full flex items-center justify-center mb-4">
              <BookOpen className="w-8 h-8 text-blue-600" />
            </div>
            <Heading size="6" className="mb-2">
              Welcome to MasteryFlow
            </Heading>
            <Text size="3" color="gray" className="mb-6">
              Your personalized learning platform powered by Whop
            </Text>
          </div>

          <div className="space-y-4">
            <div className="p-4 bg-blue-50 rounded-lg">
              <div className="flex items-center gap-2 mb-2">
                <Sparkles className="w-4 h-4 text-blue-600" />
                <Text size="2" weight="medium" color="blue">
                  AI-Powered Learning
                </Text>
              </div>
              <Text size="2" color="gray">
                Get personalized quizzes and feedback generated by AI
              </Text>
            </div>

            <div className="p-4 bg-green-50 rounded-lg">
              <Text size="2" weight="medium" color="green" className="mb-1">
                🎯 Interactive Learning
              </Text>
              <Text size="2" color="gray">
                Track your progress with gamification and achievements
              </Text>
            </div>

            <div className="p-4 bg-purple-50 rounded-lg">
              <Text size="2" weight="medium" color="purple" className="mb-1">
                📊 Analytics Dashboard
              </Text>
              <Text size="2" color="gray">
                Detailed insights into your learning journey
              </Text>
            </div>
          </div>

          <div className="mt-8">
            <Text size="2" color="gray">
              Please access this app through the Whop platform to get started.
            </Text>
          </div>
        </Card>
      </div>
    </div>
  )
}
